# Generated by Django 5.1.6 on 2026-02-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('parental_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('biotype', models.CharField(blank=True, max_length=255, null=True)),
                ('chromosome', models.CharField(max_length=255)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField(blank=True, null=True)),
                ('strand', models.CharField(max_length=255)),
                ('summit', models.IntegerField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='assembly.assembly')),
            ],
            options={
                'db_table': 'interval',
                'ordering': ['id'],
            },
        ),
    ]
