# Generated by Django 5.1.6 on 2026-02-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assay', '0001_initial'),
        ('interval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cell', 'cell'), ('spot', 'spot')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('x_coordinate', models.IntegerField(blank=True, null=True)),
                ('y_coordinate', models.IntegerField(blank=True, null=True)),
                ('z_coordinate', models.IntegerField(blank=True, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='assay.assay')),
            ],
            options={
                'db_table': 'cell',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.FloatField()),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('padj_value', models.FloatField(blank=True, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='assay.assay')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.cell')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='interval.interval')),
            ],
            options={
                'db_table': 'signal',
                'ordering': ['id'],
            },
        ),
    ]
