# Generated by Django 5.1.6 on 2026-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'assembly',
                'ordering': ['id'],
            },
        ),
    ]
