# Generated by Django 5.1.6 on 2026-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('external_repo', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study',
                'ordering': ['id'],
            },
        ),
    ]
