# Generated by Django 5.1.6 on 2026-02-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('tissue', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment', models.TextField()),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(max_length=255)),
                ('kit', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('assemblies', models.TextField(blank=True, help_text='CSV list of assemblies used in this assay', null=True)),
                ('interval_count', models.IntegerField(blank=True, null=True)),
                ('signal_nonzero', models.IntegerField(blank=True, null=True)),
                ('signal_zero', models.IntegerField(blank=True, null=True)),
                ('cell_total', models.IntegerField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='pipelines.pipeline')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='studies.study')),
            ],
            options={
                'db_table': 'assay',
                'ordering': ['id'],
            },
        ),
    ]
